### ISSUE TITLE
Apply function does not work in limiting cases

### ISSUE THREAD

**Issue by pawan1992** [SEELab/trophic-aggregations#10]
`gc[2:nl]=apply(AT[1:(nl-1),1:nl],1,sum)`

**gives an error** when nl = 2, i.e. _dim AT_ becomes 1. 
Is there a way to rectify that or _should we use a for loop instead to assign the values to the Grazing Chain?_

**Comment by pawan1992** [comment]
worked it out. A[a:b,c:d,drop=FALSE] fixes it!

**Comment by MKLau** [comment]
If the issue is that AT is treated as a vector (i.e., the number of dimensions = 1) when nl = 2, try using a logical function for this special case.

**Comment by pawan1992** [comment]
@MKLau Yes, I thought of using a logical function that but R lets you use the limiting case by setting the drop to false... the line of code that I used above demonstrates that!
`A[a:b,c:d,drop=FALSE]' would not give you problems if A is a vector. drop assumes the value TRUE by default and produces the error.
