### ISSUE TITLE
Grouping Columns in data.frame

### ISSUE THREAD

**Issue by pawan1992** [SEELab/trophic-aggregations#11]
@MKLau Matt! 
Are you aware of a method to group columns or column-names in data.frames? 
I want the NODES written somewhere in between the columns depicting the Nodes in the Cycle.
Do you think it's possible?
![screen shot 2014-07-18 at 3 51 08 pm](https://cloud.githubusercontent.com/assets/7850628/3631270/fab862dc-0eb4-11e4-9410-1c0139d0b407.png)

**Comment by pawan1992** [comment]
Presently, the `colnames(c10$Table.cycle)[3]' is NODES and the colnames after it are ' ' <blank spaces>
Could we make it better looking? Or do you think its fine?

**Comment by MKLau** [comment]
I think it looks fine the way it is. It's much more organized now.

**Comment by pawan1992** [comment]
Alright!. That works for me! 
I've pushed stable codes for the three functions. Do have a look at the outputs! Thanks.
