### ISSUE TITLE
Summary statistics for the enaTroAgg function

### ISSUE THREAD

**Issue by pawan1992** [SEELab/trophic-aggregations#12]
The troAgg function returns:
1. 1 list containing details about feeding cycles
2. 1 matrix
3. 7 vectors including the Lindeman spine
4. and the following 3 values quantifying the Detrital pool as 1 list. "ns"
   
   ```
     *Detritivory
     *Input to the Detrital pool
     *Circulation within detrital pool
   ```

The above 3 values constitute the list ns. But they are essentially just the "detrital pool" characteristics. It is okay to call them network statistics! right?

**Comment by borretts** [comment]
If I understand correctly, I think the values of the three properties listed above work as "network statistics".

**Comment by pawan1992** [comment]
yes. I think so too. And so I've put them that way.
