### ISSUE TITLE
Please review the help files in man.

### ISSUE THREAD

**Issue by pawan1992** [SEELab/trophic-aggregations#13]
The functions and help files are both done!.
The 3 functions are stored in the folder 'R'.
The corresponding help files are stored in the folder 'man'.

Kindly review it and we are ready to post it on the repo enaR in a new branch!

**Comment by borretts** [comment]
Is Beta 3 the active branch?

**Comment by MKLau** [comment]
Looks like it. It's the only branch that has R and man folders.

**Comment by pawan1992** [comment]
Yes. beta3 is the active branch. Its the one I've been doing all the manipulations in.
My apologies for not mentioning that.

**Comment by borretts** [comment]
I have reviewed the help files, and I think they are sufficient.  Thus, I am closing this issue.
