### ISSUE TITLE
add living vector check to enaTroAgg 

### ISSUE THREAD

**Issue by borretts** [SEELab/trophic-aggregations#14]
enaTroAgg assumes that the living nodes proceed the non-living nodes.  Therefore, we need to add a check of this condition to the function.

**Comment by pawan1992** [comment]
added living vector check in enaTroAgg() and also to cycliv() in case users use it independently.

**Comment by MKLau** [comment]
Sweet, thanks Stuart!

Sent using CloudMagichttps://cloudmagic.com/k/d/mailapp?ct=pa&cv=5.0.19&pv=4.1.2

On Mon, Jul 21, 2014 at 6:27 PM, Pawan <notifications@github.com<mailto:notifications@github.com>> wrote:

added living vector check in enaTroAgg() and also to cycliv() in case users use it independently.
