### ISSUE TITLE
create function to re-order model so that living nodes all preced the non-living nodes

### ISSUE THREAD

**Issue by borretts** [SEELab/trophic-aggregations#15]
We discussed two possible ways:
1.  User supplies a new node order vector
2.  Automatically move non-living nodes to the end of the node vector -- minimizing the order change for other nodes.  I think this should be the default behavior.

**Comment by pawan1992** [comment]
Created the function as desired and uploaded. It is called _Order()_ for now. [because _order()_ is already a function in the base package]
Creating a short help file now.
Whether it should be renamed to something else? Or is it okay! A bit confusing though.

**Comment by MKLau** [comment]
Can you generalize the function to order the network based on any numeric or categorical vector?

Sent using CloudMagichttps://cloudmagic.com/k/d/mailapp?ct=pa&cv=5.0.19&pv=4.1.2

On Mon, Jul 21, 2014 at 7:24 PM, Pawan <notifications@github.com<mailto:notifications@github.com>> wrote:

Created the function as desired and uploaded. It is called Order() for now. [because order() is already a function in the base package]
Creating a short help file now.
Whether it should be renamed to something else? Or is it okay! A bit confusing though.

**Comment by pawan1992** [comment]
Either the user can enter an ordering vector that contains a permutation of (1:N) {N: no of nodes} or the default is bringing the non-living nodes in the end. I guess that's the most general approach!
The only constraint is it should be a network class object as used in enaR's data sets.

Do you have any further generalization in mind?

**Comment by MKLau** [comment]
No that's good.

In that case, Order is possibly confusing, but maybe netOrder?

Sent using CloudMagichttps://cloudmagic.com/k/d/mailapp?ct=pa&cv=5.0.19&pv=4.1.2

On Mon, Jul 21, 2014 at 7:38 PM, Pawan <notifications@github.com<mailto:notifications@github.com>> wrote:

Either the user can enter an ordering vector that contains a permutation of (1:N) {N: no of nodes} or the default is bringing the non-living nodes in the end. I guess that's the most general approach!
The only constraint is it should be a network class object as used in enaR's data sets.

Do you have any further generalization in mind?

**Comment by pawan1992** [comment]
netOrder it is. Renamed and uploaded.

**Comment by MKLau** [comment]
Thanks Pawan!

On Jul 22, 2014, at 11:12 AM, Pawan wrote:

netOrder it is. Renamed and uploaded.

—
Reply to this email directly or view it on GitHubhttps://urldefense.proofpoint.com/v1/url?u=https://github.com/SEELab/trophic-aggregations/issues/15%23issuecomment-49752581&k=AjZjj3dyY74kKL92lieHqQ%3D%3D%0A&r=vNWfnnh49liNIR3izm8gF2Pf0OgxJRysf%2BQDMPpoOPk%3D%0A&m=yDb2ebWteGQQGaw3qri1boBbpXMR%2Fsuw8%2BGbMJf%2ByO8%3D%0A&s=2379e8cf51e70e29610d0bccbe3dc043ace90532e4f6f4b3394ed93e797da97f.

Postdoctoral Researcher
Harvard Forest
324 N Main St.
Petersham, MA 01366

"I am not young enough to know everything."
- Oscar Wilde
