### ISSUE TITLE
Living nodes total

### ISSUE THREAD

**Issue by MKLau** [SEELab/trophic-aggregations#2]
Hey Pawan, check the line where you sum the living nodes. x%v%"living" is a logical vector.

**Comment by pawan1992** [comment]
yes. It considers 'true' as a 1 and 'false' as 0 and therefore gives us the no. of living nodes.

**Comment by MKLau** [comment]
Ok, that makes sense, sorry, it wasn't clear from the annotation. I thought you might be trying to get the storage in living nodes.

Sent using CloudMagichttps://cloudmagic.com/k/d/mailapp?ct=pa&cv=1.0.21.2&pv=4.1.2

On Tue, Jul 01, 2014 at 10:42 PM, Pawan <notifications@github.com<mailto:notifications@github.com>> wrote:

yes. It considers 'true' as a 1 and 'false' as 0 and therefore gives us the no. of living nodes.

**Comment by pawan1992** [comment]
Its alright. I guess that solves it!.

**Comment by MKLau** [comment]
Yes! Mistaken bug squashed.
