### ISSUE TITLE
Pseudo-Code: Cycle Bases from Ulanowicz 1983

### ISSUE THREAD

**Issue by MKLau** [SEELab/trophic-aggregations#6]
1. Identify all simple cycles (i.e., the only node that occurs twice in a cycle is the originating node)
2. Calculate the circuit probabilities = (flow / sum(outputs from origin node))
3. Identify the smallest critical arc = smallest flow 
4. Divide the smallest critical arc among all the cycles in which it appears weighted by the respective circuit probabilities
5. Reassess and repeat 2-5.

**Comment by MKLau** [comment]
Ulanowicz uses a backtracking, depth-first search for #1 above.

**Comment by pawan1992** [comment]
The pseudo code for the Cycle bases as derived from NETWRK 4.2b is as:

# Pseudo code for NETWRK full cycle analysis
1. Check for presence of cycling (Check for Incoming cycle arcs in each node)
2. Arrange nodes by decreasing no. of incoming cycle arcs.
3. Find the smallest arc in the cycling nodes (:= ARCMIN = web[IMIN,JMIN])
4. IF smallest arc is a self loop. TREAT SEPARATELY.(slf.loop<-TRUE;break)
5. Else, Find the members of this nexus(nodes accessible from JMIN in forward AND IMIN in the backward direction)
6. If no cycling is found, (web[IMIN,JMIN] <- -web[IMIN,JMIN]
7. Repeat steps 2-5 till there is a cycle found in NEXUS. (till NSTP2>0)
8. Use backtracking routine to identify cycle.
9. Calculate circuit probability for current cycle
10. Add weight to temp storage matrix
11. Report this cycle
12. Repeat steps 8-11 for every cycle in the nexus
13. Normalize probability matrix.
14. Subtract proper amount from flow matrix
15. Add proper amounts to cycle distribution
16. Zero the weak arc
17. Treat the self loop, if detected.
18. repeat step 1-17 till cycles are not present. (Exit from 1)
19. Report overall results.
