### ISSUE TITLE
Checking Cycle2 code 

### ISSUE THREAD

**Issue by MKLau** [SEELab/trophic-aggregations#7]
- Cone springs output matches Ulanowicz's (Math. Bios. 1983)
- Printing and output should be standardized
- Need to generate the man file
- Needs to fit naming conventions
- Currently checking the output and runtime for several other models

**Comment by borretts** [comment]
As part of this list, we need to identify the analytical objects that the function returns.  This should include a ns vector of summary statistics (ie., number of weak arcs).
