### ISSUE TITLE
Names of the functions: enaTrophic or enaLindeman

### ISSUE THREAD

**Issue by pawan1992** [SEELab/trophic-aggregations#9]
The function gives the 11 results for the `Lindeman Trophic Aggregations` in NETWRK. I hope that all the existing users are aware of the fact that this is **Lindeman's** Trophic Analysis. 
I would speculate that _enaTrophic_ can be confused with the _Trophic_ Models to the new users. And since (if) **Lindeman spine** is something that the users want, **enaLindeman** would lead them to the function more intuitively.

Any suggestions?

**Comment by borretts** [comment]
I would be fine with naming this function enaLindeman.  Alternatively, we could name it enaLTA, thought that is not very intuitive.

**Comment by MKLau** [comment]
Agreed. We should try to keep the length down as well. Also, since Lindeman is part of the name for both analyses, we should avoid using it. Here are some ideas:

_Lindeman's Trophic Analysis_
enaLTA
enaTroAgg
enaAgg
enaLind

_Lindeman Spine_
enaSpine
enaLS
enaLspine

**Comment by borretts** [comment]
For LIndeman Spine, I like enaLspine or enaTroSpine.

For LTA, I am favoring enaLind or enaTroAgg.    

The later two names emphasize what the function does, rather than highlighting Lindeman.

**Comment by pawan1992** [comment]
I'm on-board with almost all of the Ideas. enaTroAgg sounds good. 
@MKLau Matt! do you suggest that we should split the Trophic Aggregations into 2 functions? One providing with the trophic aggregations and other with the Lindeman Spine? 
For now its just one function producing all of the data.

**Comment by MKLau** [comment]
Sorry, no, I mistakenly thought you were talking about two function. Keep it together.

Sent using CloudMagichttps://cloudmagic.com/k/d/mailapp?ct=pa&cv=5.0.11&pv=4.1.2

On Tue, Jul 15, 2014 at 5:07 PM, Pawan <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm on-board with almost all of the Ideas. enaTroAgg sounds good.
@MKLauhttps://urldefense.proofpoint.com/v1/url?u=https://github.com/MKLau&k=AjZjj3dyY74kKL92lieHqQ%3D%3D%0A&r=vNWfnnh49liNIR3izm8gF2Pf0OgxJRysf%2BQDMPpoOPk%3D%0A&m=reLDd4VSJf8ZfofmkMdpg38%2BvoUQq%2FYws7anmHHx3s4%3D%0A&s=dc262542234a20e7255e52027ab8bde5b1ac810a2046ab264735240a07e923f7 Matt! do you suggest that we should split the Trophic Aggregations into 2 functions? One providing with the trophic aggregations and other with the Lindeman Spine?
For now its just one function producing all of the data.

**Comment by pawan1992** [comment]
The final names of the functions are as follows:
- For the trophic aggregations  := enaTroAgg
- For the full cycle analysis :=       enaCycle
